# Generated by Django 3.2.2 on 2021-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainmod',
            table='maintab',
        ),
    ]
