# Generated by Django 3.2.2 on 2021-05-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0002_alter_mainmod_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mainmod',
        ),
    ]
