# Generated by Django 3.2.2 on 2021-05-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0004_mainmod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mainmod',
        ),
    ]
