# Generated by Django 3.2.2 on 2021-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0006_mainmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Login_Details',
            },
        ),
        migrations.DeleteModel(
            name='mainmod',
        ),
    ]
