# Generated by Django 3.2.2 on 2021-06-06 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0007_auto_20210606_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
