# Generated by Django 3.2.2 on 2021-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0008_auto_20210606_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(default='NULL', max_length=254),
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(default='NULL', max_length=32),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterModelTable(
            name='loginmodel',
            table='User_Details',
        ),
    ]
