# Generated by Django 3.2.2 on 2021-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0009_auto_20210607_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
