# Generated by Django 3.2.2 on 2021-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0010_alter_loginmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
