# Generated by Django 3.2.2 on 2021-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0012_auto_20210609_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='confirmpassword',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
