# Generated by Django 3.2.2 on 2021-06-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0013_auto_20210610_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='email',
            field=models.EmailField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
