# Generated by Django 3.2.2 on 2021-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0014_auto_20210610_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginmodel',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='loginmodel',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
