# Generated by Django 3.2.2 on 2021-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0015_auto_20210610_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=6)),
                ('time', models.TimeField()),
                ('fromplace', models.CharField(max_length=32)),
                ('toplace', models.CharField(max_length=32)),
                ('e_numseats', models.IntegerField()),
                ('b_numseats', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Flight_Details',
            },
        ),
    ]
