# Generated by Django 3.2.2 on 2021-06-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0016_flightdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetails',
            name='price',
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='b_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='e_price',
            field=models.IntegerField(null=True),
        ),
    ]
