# Generated by Django 3.2.2 on 2021-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0017_auto_20210615_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='b_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='e_price',
            field=models.IntegerField(),
        ),
    ]
