# Generated by Django 3.2.2 on 2021-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0019_flightdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='role',
            field=models.CharField(default='Customer', max_length=12),
        ),
    ]
