# Generated by Django 3.2.2 on 2021-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0021_remove_flightdetails_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6)),
                ('time', models.TimeField()),
                ('fromplace', models.CharField(max_length=32)),
                ('toplace', models.CharField(max_length=32)),
                ('num_passangers', models.IntegerField()),
                ('total', models.IntegerField()),
                ('paymentmode', models.CharField(max_length=16)),
                ('flightclass', models.CharField(max_length=8)),
                ('seatnumbers', models.SlugField()),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
