# Generated by Django 3.2.2 on 2021-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0022_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='seatnumbers',
            field=models.SlugField(default=' '),
        ),
    ]
