# Generated by Django 3.2.2 on 2021-06-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0026_auto_20210617_0138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactions',
            table='Flight_Transactions',
        ),
    ]
