# Generated by Django 3.2.2 on 2021-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0028_auto_20210617_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='mealpreferance',
            field=models.CharField(default='Vegetarian', max_length=16),
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='Transactions',
        ),
    ]
