# Generated by Django 3.2.2 on 2021-06-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0029_auto_20210617_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='flightdate',
            field=models.DateField(default='2021-06-17'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='flighttime',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
