# Generated by Django 3.2.2 on 2021-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0031_alter_transactions_seatnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
