# Generated by Django 3.2.2 on 2021-06-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesite', '0032_alter_transactions_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_num',
            field=models.IntegerField(default=0),
        ),
    ]
